---
# Mise en place des variables dans SSM:
ansible_server_name: "{{ lookup('aws_ssm', '/' ~ environnement ~ '/' ~ application ~ '/ansible_site_server_name',region='eu-west-1' ) }}"
ansible_nginx_upstream: "{{ environnement }}-{{ application }}-site"
ansible_nginx_log: "{{ ansible_server_name }}"

# Nginx
nginx_remove_default_vhost: false
nginx_worker_processes: "auto"
nginx_error_log: "/var/log/nginx/error.log"
nginx_access_log: "/var/log/nginx/access.log main"
nginx_extra_conf_options: |
  include /usr/share/nginx/modules/*.conf;
nginx_extra_http_options: |
  types_hash_max_size 2048;

nginx_vhosts:
  # advoko site
  - listen: "80"
    server_name: "{{ ansible_server_name }}"
    access_log: "/var/log/nginx/{{ ansible_nginx_upstream }}.log main"
    root: "/usr/share/nginx/html"

    extra_parameters: |
      listen       [::]:80;
      server_tokens off;

        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
          proxy_redirect off;
        }
        location /checkHealth {
          return 404 'Not Found';
          add_header Content-Type text/plain;
        }

nginx_remove_default_vhost: true

# nginx log format
nginx_log_format: |-
   '$host $remote_addr - $remote_user [$time_local] "$request" '
   '$status $body_bytes_sent "$http_referer" '
   '"$http_user_agent" $request_time "$request_body" "$http_x_forwarded_for"'

# Vars for packages
yum_needed_packages:
  - epel-release
  - unzip
  - vim
  - git
  - wget
  - curl
  - python-pip
  - nano

pip_needed_packages:
  - awscli

# Folders for advoko
pathtoadvoko:
  - "~/logs"
  - "~/buildpacker"
  - "~/advoko"
...
